# generated by chatGPT

def load_cell_mapping(filename):
    mapping = {}
    with open(filename) as f:
        for line in f:
            name, var = line.strip().split()
            mapping[int(var)] = name
    return mapping

def load_solution(filename):
    with open(filename) as f:
        for line in f:
            if line.startswith('SAT'):
                continue
            return set(int(x) for x in line.strip().split() if int(x) > 0)

def build_grid(mapping, solution):
    # Extract coordinates and determine grid size
    coords = [tuple(map(int, name.split('_')[1:])) for name in mapping.values()]
    max_row = max(r for r, c in coords)
    max_col = max(c for r, c in coords)
    
    # Build reverse mapping from var -> (row, col)
    var_to_pos = {var: tuple(map(int, name.split('_')[1:])) for var, name in mapping.items()}
    
    # Initialize grid
    grid = [['.' for _ in range(max_col + 1)] for _ in range(max_row + 1)]
    
    for var in solution:
        if var in var_to_pos:
            row, col = var_to_pos[var]
            grid[row][col] = '#'
    
    return grid

def print_grid(grid):
    for row in grid:
        print(''.join(row))

# ==== Main ====
if __name__ == "__main__":
    cell_file = "cells_def.txt"
    solution_file = "solution.txt"

    mapping = load_cell_mapping(cell_file)
    solution = load_solution(solution_file)
    grid = build_grid(mapping, solution)
    print_grid(grid)
